steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: 'functions/licenceAppointments'
- name: 'gcr.io/cloud-builders/npm'
  args: ['test']
  dir: 'functions/licenceAppointments'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'licenceAppointments', '--trigger-http', '--runtime=nodejs8', '--timeout=540000']
  dir: 'functions/licenceAppointments'